---
- name: create s3 bucket
  hosts: sonarqube
  vars_files:
    - awscredentials.yml
    - bucketdetails.yml
  tasks: 
    - name: create s3 bucket
      s3:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       region: "{{ aws_default_region }}"
       bucket: "{{ bucketname }}"
       state: present
         #aws_access_key: "{{ aws_access_key }}"
         #aws_secret_key: "{{ aws_secret_key }}"
         #region: "{{ aws_default_region }}"
       mode: create

    - name: Upload backup file to s3
      s3:
       name: "{{ bucketname }}"
       object: "{{ file }}"
       src: "{{ path }}"
       mode: put

    
